spring.application.name=bridgepay-notification-service

spring.cloud.aws.region.static=us-east-1
app.sqs.payment-results-queue-url=${SQS_PAYMENT_RESULTS_QUEUE_URL}
app.sqs.dlq-url=${SQS_DLQ_URL}

notifications.enabled=${NOTIFICATIONS_ENABLED:false}
aws.sns.region=${AWS_REGION:us-east-1}
sendgrid.api-key=${SENDGRID_API_KEY:}
