spring.application.name=bridgepay-notification-service

spring.cloud.aws.region.static=us-east-1
app.sqs.queue-url=https://sqs.us-east-1.amazonaws.com/071292885046/bridgepay-payment-events
app.sqs.dlq-url=https://sqs.us-east-1.amazonaws.com/071292885046/bridgepay-payment-events-dlq

notifications.enabled=${NOTIFICATIONS_ENABLED:false}
aws.sns.region=${AWS_REGION:us-east-1}
sendgrid.api-key=${SENDGRID_API_KEY:}
